"""Tests for the Token data contract (tokens.py).

Plan 00-03 — RED phase: all tests must FAIL against the stub implementation.
"""

from __future__ import annotations

import sys

import pytest


def test_T1_token_type_has_19_members():
    """TokenType enum has exactly 19 members."""
    from atena.tokens import TokenType

    assert len(list(TokenType)) == 19


def test_T2_token_construction_and_field_access():
    """Token constructs without error and fields are readable."""
    from atena.tokens import Token, TokenType

    token = Token(
        type=TokenType.NUMBER,
        value="42",
        line=3,
        col=0,
        source_line="x = 42",
    )
    assert token.line == 3
    assert token.value == "42"
    assert token.col == 0
    assert token.source_line == "x = 42"


def test_T3_token_equality_via_dataclass():
    """Two Token instances with identical fields compare equal."""
    from atena.tokens import Token, TokenType

    t1 = Token(type=TokenType.IDENTIFIER, value="score", line=1, col=0, source_line="score = 10")
    t2 = Token(type=TokenType.IDENTIFIER, value="score", line=1, col=0, source_line="score = 10")
    assert t1 == t2


def test_T4_keywords_show_and_function():
    """KEYWORDS maps 'show' and 'function' to TokenType.KEYWORD."""
    from atena.tokens import KEYWORDS, TokenType

    assert KEYWORDS["show"] == TokenType.KEYWORD
    assert KEYWORDS["function"] == TokenType.KEYWORD


def test_T5_keywords_has_18_entries():
    """KEYWORDS dict has exactly 18 Atena keyword entries."""
    from atena.tokens import KEYWORDS

    assert len(KEYWORDS) == 18


def test_T6_user_identifiers_not_in_keywords():
    """User-defined identifiers are not in the keyword map."""
    from atena.tokens import KEYWORDS

    assert "score" not in KEYWORDS
    assert "x" not in KEYWORDS
    assert "name" not in KEYWORDS


def test_T7_token_repr_contains_field_names():
    """Token __repr__ (auto-generated by @dataclass) contains field names."""
    from atena.tokens import Token, TokenType

    token = Token(type=TokenType.STRING, value="hello", line=2, col=4, source_line='show "hello"')
    r = repr(token)
    assert "type" in r
    assert "value" in r
    assert "line" in r
