# Generated by Atena
def _atena_index(i):
    if i < 1:
        raise IndexError("List positions in Atena start at 1.")
    return i - 1


def _atena_concat(a, b):
    return str(a) + str(b)
name = input("Enter student name: ")
g1 = 8
g2 = 6
g3 = 9
g4 = 7
grades = [g1, g2, g3, g4]
student = {"name": "waiting", "passed": False}


def make_greeting(n):
    return _atena_concat("Welcome, ", n)


def is_passing(score):
    if score >= 6:
        return "pass"
    else:
        return "fail"
print(make_greeting(name))
total = g1 + g2 + g3 + g4
avg = total / 4
verdict = is_passing(avg)
print(_atena_concat("Your average is: ", str(avg)))
print(_atena_concat("Result: ", verdict))
if avg >= 6:
    student["passed"] = True
else:
    student["passed"] = False
student["name"] = name
print(_atena_concat("Student on record: ", student["name"]))
grades.append(10)
print(_atena_concat("After bonus grade, count: ", str(len(grades))))
grades.remove(10)
print(_atena_concat("After removal, count: ", str(len(grades))))
print(_atena_concat("First grade: ", str(grades[0])))
i = 2
print(_atena_concat("Grade at position 2: ", str(grades[_atena_index(i)])))
j = 1
while j <= 3:
    j = j + 1
print(_atena_concat("Counted to: ", str(j)))
count = 0
for _atena_i0 in range(2):
    for _atena_i1 in range(2):
        count = count + 1
print(_atena_concat("Nested repeat count: ", str(count)))